AspNetCourseProject/FanFictionApp/Areas/Administration/Controllers/AdminsController.cs
namespace FanFictionApp.Areas.Administration.Controllers
{
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Identity;
	using FanFiction.Services.Utilities;
	using FanFiction.Services.Interfaces;
	using FanFiction.ViewModels.InputModels;
	using Microsoft.AspNetCore.Authorization;
	using FanFiction.ViewModels.OutputModels.Users;

	[Area(GlobalConstants.RouteConstants.Administration)]
	[Authorize(Roles = "admin,moderator")]
	public class AdminsController : Controller
	{
		public AdminsController(IAdminService adminService, IStoryService storyService)
		{
			this.AdminService = adminService;
			this.StoryService = storyService;
		}

		protected IAdminService AdminService { get; }
		protected IStoryService StoryService { get; }

		[HttpGet]
		[Authorize(Roles = GlobalConstants.Admin)]
		public IActionResult AllUsers()
		{
			var model = this.AdminService.AllUsers().Result;

			return View(model);
		}

		[HttpGet]
		public IActionResult AllStories()
		{
			var model = this.StoryService.CurrentStories(null);

			return View(model);
		}

		[HttpGet]
		public IActionResult AllAnnouncements()
		{
			var model = this.AdminService.AllAnnouncements();

			return View(model);
		}

		[HttpGet]
		public IActionResult DeleteAnnouncement(int Id)
		{
			this.AdminService.DeleteAnnouncement(Id);
			return RedirectToAction("AllAnnouncements");
		}

		[HttpGet]
		public IActionResult DeleteAllAnnouncements()
		{
			this.AdminService.DeleteAllAnnouncements();
			return RedirectToAction("AllAnnouncements");
		}

		[HttpPost]
		public IActionResult AllAnnouncements(AnnouncementInputModel inputModel)
		{
			if (ModelState.IsValid)
			{
				this.AdminService.AddAnnouncement(inputModel);
				return RedirectToAction(nameof(AllAnnouncements));
			}

			this.ViewData[GlobalConstants.Error] = GlobalConstants.TooShortAnnouncement;
			return RedirectToAction(nameof(AllAnnouncements));
		}

		[HttpGet]
		[Authorize(Roles = GlobalConstants.Admin)]
		public async Task<IActionResult> DeleteUSer(string id)
		{
			await this.AdminService.DeleteUser(id);

			return RedirectToAction("AllUsers");
		}

		[HttpGet]
		[Authorize(Roles = GlobalConstants.Admin)]
		public IActionResult EditRole(string id)
		{
			var model = this.AdminService.AdminModifyRole(id);
			return View(model);
		}

		[HttpPost]
		[Authorize(Roles = GlobalConstants.Admin)]
		public IActionResult EditRole(ChangingRoleModel inputModel)
		{
			var result = this.AdminService.ChangeRole(inputModel).Result;

			if (result == IdentityResult.Success)
			{
				return RedirectToAction(nameof(AllUsers));
			}

			return RedirectToAction("Error", "Home");
		}

		[HttpGet]
		public async Task<IActionResult> DeleteStory(int Id)
		{
			if (!this.User.IsInRole(GlobalConstants.Admin) && !this.User.IsInRole(GlobalConstants.Moderator))
			{
				return RedirectToAction("Error", "Home", "");
			}

			string username = this.User.Identity.Name;

			await this.StoryService.DeleteStory(Id, username);

			return RedirectToAction(nameof(AllStories));
		}

		[HttpGet]
		public IActionResult CurrentGenres()
		{
			var model = this.StoryService.Genres();

			return this.View(model);
		}

		[HttpPost]
		public IActionResult CurrentGenres(string name)
		{
			var genres = this.StoryService.Genres();

			if (string.IsNullOrEmpty(name))
			{
				this.ViewData[GlobalConstants.Error] = GlobalConstants.NullName;
				return this.View(genres);
			}

			var result = this.AdminService.AddGenre(name);

			if (result != GlobalConstants.Success)
			{
				string error = string.Format(GlobalConstants.AlreadyExistsInDb, name);
				this.ViewData[GlobalConstants.Error] = error;
				return this.View(genres);
			}

			return RedirectToAction(nameof(CurrentGenres));
		}
	}
}

AspNetCourseProject/FanFictionApp/Controllers/CommentsController.cs
namespace FanFictionApp.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using FanFiction.Services.Interfaces;
	using FanFiction.Services.Utilities;
	using FanFiction.ViewModels.InputModels;
	using Microsoft.AspNetCore.Authorization;

	[Authorize]
	public class CommentsController : Controller
	{
		public CommentsController(ICommentService commentService)
		{
			this.CommentService = commentService;
		}

		protected ICommentService CommentService { get; set; }

		[HttpGet]
		public IActionResult DeleteComment(int storyId, int id)
		{
			this.CommentService.DeleteComment(id);

			return RedirectToAction("Details", "Stories", new { id = storyId });
		}

		[HttpPost]
		public IActionResult AddComment(CommentInputModel inputModel)
		{
			if (!ModelState.IsValid)
			{
				this.TempData[GlobalConstants.Error] = GlobalConstants.CommentsLength;
				return RedirectToAction("Details", "Stories", new { id = inputModel.StoryId });
			}
			this.CommentService.AddComment(inputModel);

			return RedirectToAction("Details", "Stories", new { id = inputModel.StoryId });
		}

		[HttpGet]
		public IActionResult DeleteCommentFromInfoHub(int id)
		{
			this.CommentService.DeleteComment(id);

			return RedirectToInfohub();
		}

		[HttpGet]
		public IActionResult DeleteAllComments(string username)
		{
			this.CommentService.DeleteAllComments(username);

			return RedirectToInfohub();
		}

		private IActionResult RedirectToInfohub()
		{
			var username = this.User.Identity.Name;

			return RedirectToAction("Infohub", "Messages", new { username });
		}
	}
}

AspNetCourseProject/FanFictionApp/Controllers/NotificationsController.cs
namespace FanFictionApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using FanFiction.Services.Interfaces;
    using Microsoft.AspNetCore.Authorization;

    [Authorize]
    public class NotificationsController : Controller
    {
        public NotificationsController(INotificationService notificationService)
        {
            this.NotificationService = notificationService;
        }

        protected INotificationService NotificationService { get; }

        public IActionResult DeleteNotification(int id)
        {
            this.NotificationService.DeleteNotification(id);

            return RedirectToInfohub();
        }

        public IActionResult DeleteAllNotifications(string username)
        {
            this.NotificationService.DeleteAllNotifications(username);
            return RedirectToInfohub();
        }

        public IActionResult MarkNotificationAsSeen(int id)
        {
            this.NotificationService.MarkNotificationAsSeen(id);

            return RedirectToInfohub();
        }

        private IActionResult RedirectToInfohub()
        {
            var username = this.User.Identity.Name;

            return RedirectToAction("Infohub", "Messages", new { username });
        }
    }
}

AspNetCourseProject/FanFictionApp/Views/Shared/AnnouncementCreatePartial.cshtml
@model AnnouncementInputModel

<div class="justify-content-center col-md-4">
    <h5 class="text-center">Publish Announcement</h5>

    <div class="col-md-12">
        <form asp-controller="Admins" asp-action="AllAnnouncements" asp-area="Administration" style="border: 1px solid black" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Author" type="hidden" class="form-control text-center" value="@User.Identity.Name" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <label class="control-label text-center">Announcement</label>
                <textarea asp-for="Content" class="form-control" rows="4">
                </textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">

                <a class="btn btn-link align-content-end" asp-area="Administration" asp-controller="Admins" asp-action="DeleteAllAnnouncements">DeleteAll</a>

                <input type="submit" value="Create" style="align-content: center" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
}

AspNetCourseProject/FanFictionApp/Views/Shared/CommentsInfohubPartial.cshtml
@model IEnumerable<CommentOutputModel>
@{

    int count = 0;
}

<div class="container  col-md-12  table-responsive">

    <table class="table table-bordered table-hover" id="dataFromDb4">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Comment</th>
                <th scope="col" class="text-center">Date Added</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody class="text-white">
            @foreach (var m in Model)
            {

                {
                    count++;
                }
                <tr>
                    <th scope="row" class="text-center">@count</th>
                    <td class="text-center">@m.Message</td>
                    <td class="text-center">@m.CommentedOn</td>

                    <td>
                        <div class=" d-flex justify-content-around">

                            <a asp-action="DeleteCommentFromInfoHub" asp-controller="Comments" asp-area="" asp-route-id="@m.Id" class="btn btn-dark ">Delete Comment</a>
                            @if (m.StoryId != default(int))
                            {
                                <a asp-action="Details" asp-controller="Stories" asp-area="" asp-route-id="@m.StoryId" class="btn btn-info ">Go to Story</a>
                            }
                            else
                            {
                                <a  class="btn btn-info disabled">Story Deleted</a>

                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn-group-justified">
        <a class="card-link text-dark" asp-action="DeleteAllComments" asp-controller="Comments" asp-area="" asp-route-username="@this.User.Identity.Name">Delete All Comments</a>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
    <script>
        $(document).ready(function () {
            $('#dataFromDb4').DataTable({ responsive: true });
        });
    </script>
}

AspNetCourseProject/FanFictionApp/Views/Shared/NewMessagesPartial.cshtml
@model IEnumerable<FanFiction.ViewModels.OutputModels.InfoHub.MessageOutputModel>
@{
    ViewData["Title"] = "AllStories";
    int count = 0;

}

<div class="container  col-md-12 mt-5 table-responsive">

    <table class="table table-bordered" id="dataFromDb1">
        <thead class="thead-dark">
            <tr>
                <th class="text-center" scope="col">#</th>
                <th class="text-center" scope="col">From</th>
                <th class="text-center" scope="col">Received on</th>
                <th class="text-center" scope="col">Text</th>
                <th class="text-center" scope="col">Actions</th>
            </tr>
        </thead>
        <tbody class="text-white">
            @foreach (var m in Model)
            {

                {
                    count++;
                }
                <tr>
                    <th scope="row" class="text-center">@count</th>

                    <td class="text-center">@m.Sender</td>
                    <td class="text-center">@m.SendOn.ToShortDateString()</td>
                    <td class="text-center">@m.Text</td>

                    <td>
                        <div class=" d-flex justify-content-around ">

                            <a asp-action="MessageSeen" asp-controller="Messages" asp-area="" asp-route-id="@m.Id" class="btn btn-dark ">Mark As Seen</a>
                            <a asp-action="DeleteMessage" asp-controller="Messages" asp-area="" asp-route-id="@m.Id" class="btn btn-danger ">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn-group-justified">

        <a class="card-link text-dark" asp-action="DeleteAllMessages" asp-controller="Messages" asp-route-username="@this.User.Identity.Name">Delete All Messages</a> &nbsp;
        <a class="card-link text-dark" asp-action="MarkAllMessagesAsSeen" asp-controller="Messages" asp-area="" asp-route-username="@this.User.Identity.Name">Mark All Messages</a>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
   
}

AspNetCourseProject/FanFictionApp/Views/Shared/NotificationsInfohubPartial.cshtml
@model IEnumerable<NotificationOutputModel>
@inject INotificationService notificationService
@{
    ViewData["Title"] = "AllStories";
    int count = 0;
}

<div class="container  col-md-12 mt-5 table-responsive">

    <table class="table table-bordered" id="dataFromDb2">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Notification</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody class="text-white">
            @foreach (var m in Model)
            {

                {
                    count++;
                }
                <tr>
                    <th scope="row" class="text-center">@count</th>
                    <td class="text-center">@m.Message</td>

                    <td>
                        <div class=" d-flex justify-content-around ">
                            @if (!m.Seen)
                            {
                                <a asp-action="MarkNotificationAsSeen" asp-controller="Notifications" asp-area="" asp-route-id="@m.Id" class="btn btn-dark ">Mark as Seen</a>
                            }
                            <a asp-action="DeleteNotification" asp-controller="Notifications" asp-area="" asp-route-id="@m.Id" class="btn btn-dark ">Delete Notification</a>
                            @if (this.notificationService.StoryExists(m.UpdatedStoryId))
                            {
                                <a asp-action="Details" asp-controller="Stories" asp-area="" asp-route-id="@m.UpdatedStoryId" class="btn btn-dark ">Story Details</a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn-group-justified">
        <a class="card-link text-dark" asp-action="DeleteAllNotifications" asp-controller="Notifications" asp-route-username="@this.User.Identity.Name">Delete All Notifications</a>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
    <script>
        $(document).ready(function () {
            $('#dataFromDb2').DataTable({ responsive: true });
        });
    </script>
}

AspNetCourseProject/FanFictionApp/Views/Shared/OldMessagesPartial.cshtml
@model IEnumerable<MessageOutputModel>
@{

    int count = 0;
}

<div class="container  col-md-12 mt-5 table-responsive">

    <table class="table table-bordered" id="dataFromDb3">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">From</th>
                <th scope="col" class="text-center">Send On:</th>
                <th scope="col" class="text-center">Text</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody class="text-white">
            @foreach (var m in Model)
            {

                {
                    count++;
                }
                <tr>
                    <th scope="row" class="text-center">@count</th>
                    <td class="text-center">@m.Sender</td>
                    <td class="text-center">@m.SendOn.ToShortDateString()</td>
                    <td class="text-center">@m.Text</td>

                    <td>
                        <div class=" d-flex justify-content-around ">
                            <a asp-action="DeleteMessage" asp-controller="Messages" asp-area="" asp-route-id="@m.Id" class="btn btn-dark ">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn-group-justified">
        <a class="card-link text-dark" asp-action="DeleteAllMessages" asp-controller="Messages" asp-route-username="@this.User.Identity.Name">Delete All Messages</a>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }

}

AspNetCourseProject/FanFictionApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FanFictionApp</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/reset-css.css" />
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/tabs.css" />
    <link rel="stylesheet" type="text/css" href="~/css/home.css" />
</head>
<body>
    <div class="entireDiv">
        <header>
            <nav id="navBar" class="navbar navbar-expand-md       w-100">
                <a class="navbar-brand text-white" href="/">Fan FictionApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-white"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="color: white" href="/">Home</a>
                        </li>

                        <li class="nav-item">

                            <a class="nav-link" style="color: white" asp-action="About" asp-area="" asp-controller="Home">About</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("admin") || this.User.IsInRole("moderator"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle nav-link-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span style="color: white">Administration</span>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    @if (this.User.IsInRole(GlobalConstants.Admin))
                                    {
                                        <a class="dropdown-item text-center" style="color: blue" asp-controller="Admins" asp-action="AllUsers" asp-area="Administration">Users</a>
                                    }
                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item text-center" style="color: blue" asp-controller="Admins" asp-action="AllStories" asp-area="Administration">Stories</a>
                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item text-center" style="color: blue" asp-controller="Admins" asp-action="AllAnnouncements" asp-area="Administration">Announcements</a>
                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item text-center" style="color: blue" asp-controller="Admins" asp-action="CurrentGenres" asp-area="Administration">Genres Available</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    @if (!this.User.Identity.IsAuthenticated)
                    {

                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                <a class="nav-link" id="LoginButton" style="color: white" asp-controller="Users" asp-action="Login" asp-area="">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: white" asp-controller="Users" asp-action="Register" asp-area="">Register</a>
                            </li>
                        </ul>

                    }
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" id="hello" style="color: white" asp-controller="Home" asp-action="Index">Hello @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: white" asp-controller="Users" asp-action="Logout" asp-area="">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </nav>
        </header>
        <div class="mainDiv">
            @RenderBody()
        </div>
        <footer class=" text-center  bg-dark container-fluid mx-auto" style="position: fixed; bottom: 0;right:0">
            <div>
                <p class="text-primary mx-auto pt-2">&copy;CopyRight AlienDreamer Studios 2018. All rights reserved. </p>
            </div>
        </footer>
    </div>
</body>
@RenderSection("scripts", required: false)
</html>

AspNetCourseProject/FanFictionApp/Views/Shared/_MyScriptsPartial.cshtml
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/bootstrap.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootbox.min.js"></script>
<script type="text/javascript" charset="utf8" src="~/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#dataFromDb').DataTable({
            responsive: true,
        });
    });
</script>