AspNetCourseProject/FanFictionApp/Controllers/ChaptersController.cs
namespace FanFictionApp.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using FanFiction.Services.Utilities;
	using FanFiction.Services.Interfaces;
	using FanFiction.ViewModels.InputModels;
	using Microsoft.AspNetCore.Authorization;
	using FanFiction.ViewModels.OutputModels.Chapters;

	[Authorize]
	public class ChaptersController : Controller
	{
		public ChaptersController(IChapterService chapterService)
		{
			this.ChapterService = chapterService;
		}

		public IChapterService ChapterService { get; }

		[HttpPost]
		public IActionResult AddChapter(ChapterInputModel inputModel)
		{
			if (!ModelState.IsValid)
			{
				this.ViewData[GlobalConstants.ChapterLength] = inputModel.Content?.Length ?? 0;
				this.ViewData[GlobalConstants.StoryId] = inputModel.StoryId;
				return this.View(inputModel);
			}

			this.ChapterService.AddChapter(inputModel);

			return RedirectToAction("Details", "Stories", new { id = inputModel.StoryId });
		}

		[HttpGet]
		[Route(GlobalConstants.RouteConstants.AddChapterRoute)]
		public IActionResult AddChapter(int storyId)
		{
			this.ViewData[GlobalConstants.StoryId] = storyId;
			return this.View();
		}

		[HttpGet]
		public IActionResult DeleteChapter([FromQuery]int storyId, [FromQuery] int chapterid)
		{
			string username = this.User.Identity.Name;
			this.ChapterService.DeleteChapter(storyId, chapterid, username);

			this.ViewData[GlobalConstants.RedirectAfterAction] = storyId;
			return RedirectToAction("Details", "Stories", new { id = storyId });
		}

		[HttpGet]
		public IActionResult EditChapter(int id)
		{
			var model = this.ChapterService.GetChapterToEditById(id);

			if (model == null)
			{
				return NotFound();
			}

			return this.View(model);
		}

		[HttpPost]
		public IActionResult EditChapter(ChapterEditModel editModel)
		{
			if (!ModelState.IsValid)
			{
				this.ViewData[GlobalConstants.ChapterLength] = editModel.Content?.Length ?? 0;
				return this.View(editModel);
			}

			this.ChapterService.EditChapter(editModel);

			return RedirectToAction("Details", "Stories", new { id = editModel.StoryId });
		}
	}
}

AspNetCourseProject/FanFictionApp/Controllers/CommentsController.cs
namespace FanFictionApp.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using FanFiction.Services.Interfaces;
	using FanFiction.Services.Utilities;
	using FanFiction.ViewModels.InputModels;
	using Microsoft.AspNetCore.Authorization;

	[Authorize]
	public class CommentsController : Controller
	{
		public CommentsController(ICommentService commentService)
		{
			this.CommentService = commentService;
		}

		protected ICommentService CommentService { get; set; }

		[HttpGet]
		public IActionResult DeleteComment(int storyId, int id)
		{
			this.CommentService.DeleteComment(id);

			return RedirectToAction("Details", "Stories", new { id = storyId });
		}

		[HttpPost]
		public IActionResult AddComment(CommentInputModel inputModel)
		{
			if (!ModelState.IsValid)
			{
				this.TempData[GlobalConstants.Error] = GlobalConstants.CommentsLength;
				return RedirectToAction("Details", "Stories", new { id = inputModel.StoryId });
			}
			this.CommentService.AddComment(inputModel);

			return RedirectToAction("Details", "Stories", new { id = inputModel.StoryId });
		}

		[HttpGet]
		public IActionResult DeleteCommentFromInfoHub(int id)
		{
			this.CommentService.DeleteComment(id);

			return RedirectToInfohub();
		}

		[HttpGet]
		public IActionResult DeleteAllComments(string username)
		{
			this.CommentService.DeleteAllComments(username);

			return RedirectToInfohub();
		}

		private IActionResult RedirectToInfohub()
		{
			var username = this.User.Identity.Name;

			return RedirectToAction("Infohub", "Messages", new { username });
		}
	}
}

AspNetCourseProject/FanFictionApp/Controllers/StoriesController.cs
namespace FanFictionApp.Controllers
{
	using System.Linq;
	using System.Security.Claims;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using FanFiction.Services.Utilities;
	using FanFiction.Services.Interfaces;
	using FanFiction.ViewModels.InputModels;
	using Microsoft.AspNetCore.Authorization;

	[Authorize]
	public class StoriesController : Controller
	{
		public StoriesController(IStoryService storyService)
		{
			this.StoryService = storyService;
		}

		protected IStoryService StoryService { get; }

		[HttpGet]
		public IActionResult AllStories()
		{
			var model = this.StoryService.CurrentStories(null);
			return this.View(model);
		}

		[HttpPost]
		public IActionResult AllStories(string type)
		{
			var model = this.StoryService.CurrentStories(type);
			return this.View(model);
		}

		[HttpGet]
		[Route(GlobalConstants.RouteConstants.UserStories)]
		public IActionResult UserStories(string username)
		{
			var id = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
			this.ViewData[GlobalConstants.UsernameHolder] = username;
			var userStories = this.StoryService.UserStories(id);
			return this.View(userStories);
		}

		[HttpGet]
		public IActionResult CreateStory()
		{
			return this.View();
		}

		[HttpPost]
		public async Task<IActionResult> CreateStory(StoryInputModel inputModel)
		{
			bool imageNotNull = inputModel.StoryImage != null;
			bool wrongType = false;

			if (imageNotNull)
			{
				var fileType = inputModel.StoryImage.ContentType.Split('/')[1];

				wrongType = GlobalConstants.imageFormat.Contains(fileType);
			}

			if (!ModelState.IsValid)
			{
				return this.View(inputModel);
			}

			if (!wrongType && imageNotNull)
			{
				this.ViewData[GlobalConstants.Error] = GlobalConstants.WrongFileType;
				return this.View(inputModel);
			}

			var id = await this.StoryService.CreateStory(inputModel);

			return RedirectToAction("Details", "Stories", new { id });
		}

		[HttpGet]
		public IActionResult Details(int id)
		{
			var fictionStory = this.StoryService.GetStoryById(id);
			return this.View(fictionStory);
		}

		[HttpGet]
		public async Task<IActionResult> DeleteStory(int id)
		{
			string username = this.User.Identity.Name;

			await this.StoryService.DeleteStory(id, username);

			return RedirectToAction("UserStories", "Stories", new { username });
		}

		[HttpGet]
		public async Task<IActionResult> Follow(int id)
		{
			var username = this.User.Identity.Name;
			var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
			await this.StoryService.Follow(username, userId, id);

			return RedirectToAction("Details", "Stories", new { id });
		}

		[HttpGet]
		public async Task<IActionResult> UnFollow(int id)
		{
			var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
			await this.StoryService.UnFollow(userId, id);

			return RedirectToAction("Details", "Stories", new { id });
		}

		[HttpPost]
		public IActionResult AddRating([FromForm]int storyId, [FromForm]double rating)
		{
			string username = this.User.Identity.Name;

			this.StoryService.AddRating(storyId, rating, username);

			return RedirectToAction("Details", "Stories", new { id = storyId });
		}

		[HttpGet]
		public IActionResult FollowedStories()
		{
			string name = this.User.Identity.Name;

			var model = this.StoryService.FollowedStories(name);

			return this.View(model);
		}

		[HttpPost]
		public IActionResult FollowedStories(string type)
		{
			string name = this.User.Identity.Name;

			var model = this.StoryService.FollowedStoriesByGenre(name, type);
			return this.View(model);
		}
	}
}

AspNetCourseProject/FanFictionApp/Views/ViewComponents/ChapterListViewComponent.cs
namespace FanFictionApp.Views.ViewComponents
{
	using AutoMapper;
	using System.Linq;
	using FanFiction.Data;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using System.Collections.Generic;
	using Microsoft.EntityFrameworkCore;
	using FanFiction.Services.Utilities;
	using AutoMapper.QueryableExtensions;
	using FanFiction.ViewModels.OutputModels.Chapters;

	[ViewComponent(Name = "ChapterList")]
	public class ChapterListViewComponent : ViewComponent
	{
		public ChapterListViewComponent(FanFictionContext context, IMapper mapper)
		{
			this.Context = context;
			this.Mapper = mapper;
		}

		protected IMapper Mapper { get; set; }

		protected FanFictionContext Context { get; }

		public async Task<IViewComponentResult> InvokeAsync(int storyId)
		{
			var chapters = await GetChaptersAsync(storyId);
			this.ViewData[GlobalConstants.StoryId] = storyId;
			return View(chapters);
		}

		private async Task<List<ChapterOutputModel>> GetChaptersAsync(int id)
		{
			var chapters = await this.Context.Chapters.Where(x => x.FanFictionStoryId == id).ProjectTo<ChapterOutputModel>(Mapper.ConfigurationProvider).ToListAsync();

			return chapters;
		}
	}
}

AspNetCourseProject/FanFictionApp/Views/ViewComponents/CommentsListViewComponent.cs
namespace FanFictionApp.Views.ViewComponents
{
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;
	using AutoMapper;
	using AutoMapper.QueryableExtensions;
	using FanFiction.Data;
	using FanFiction.ViewModels.OutputModels.Stories;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.EntityFrameworkCore;

	public class CommentsListViewComponent : ViewComponent
	{
		public CommentsListViewComponent(FanFictionContext context, IMapper mapper)
		{
			this.Context = context;
			this.Mapper = mapper;
		}

		protected IMapper Mapper { get; set; }

		protected FanFictionContext Context { get; }

		public async Task<IViewComponentResult> InvokeAsync(int storyId)
		{
			var comments = await GetChaptersAsync(storyId);
			this.ViewData[FanFiction.Services.Utilities.GlobalConstants.StoryId] = storyId;
			return View(comments);
		}

		private async Task<List<CommentOutputModel>> GetChaptersAsync(int id)
		{
			var comments = await this.Context.Comments.Where(x => x.FanFictionStory.Id == id).ProjectTo<CommentOutputModel>(Mapper.ConfigurationProvider).ToListAsync();

			return comments;
		}
	}
}

AspNetCourseProject/FanFictionApp/Views/Stories/AddChapter.cshtml
@model ChapterInputModel

@{
    ViewData["Title"] = "AddChapter";
    var storyId = int.Parse(ViewData[GlobalConstants.StoryId].ToString());
}
<div class="container d-flex col-md-6 offset-3 mt-5">
    <div class=" card col-md-12 w-100 mt-3" style="border: 1px solid black; min-height: 700px;max-height:100%">
        <form asp-controller="Stories" asp-action="AddChapter" asp-area="" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Author" type="hidden" class="form-control text-center" value="@User.Identity.Name" />
                <input asp-for="CreatedOn" type="hidden" class="form-control text-center" value="@DateTime.UtcNow" />
                <input asp-for="StoryId" type="hidden" class="form-control text-center" value="@storyId" />
            </div>
            <div class="form-group">
                <label class="control-label col-md-4 offset-4" style="text-align:center" name="Title">Title</label>
                <input asp-for="Title" type="text" class="form-control" name="Title" placeholder="Add title..." />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group text-center" style="max-height: 600px; overflow-y:auto ">
                <label class="control-label text-center">Add Content</label>
                <textarea asp-for="Content" class="form-control" rows="20" style="min-height:400px" id="editor"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
                @if (this.ViewData.ContainsKey(GlobalConstants.ChapterLength))
                {
                    <span class="text-danger">Currently your chapter is: @ViewData[GlobalConstants.ChapterLength] long</span>
                }
            </div>
            <div class="form-group col-md-12 text-center">
                <input type="submit" value="Create" style="align-content: center" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }

}

AspNetCourseProject/FanFictionApp/Views/Stories/AllStories.cshtml
@model IEnumerable<StoryOutputModel>
@inject IStoryService Service
@{
    ViewData["Title"] = "AllStories";
    var genres = this.Service.Genres();
    var nullAuthor = GlobalConstants.DeletedUser;
}

<div class="container-fluid">
    <div class="row mt-5 col-md-3">
        <form id="myForm" asp-action="AllStories" asp-controller="Stories">
            <div class="form-row align-items-center">
                <div class="col-auto">
                    <select class="custom-select mr-sm-2" name="type" onchange="this.form.submit">
                        <option selected>Choose...</option>
                        @foreach (var g in genres)
                        {
                            <option value="@g.Type">@g.Type</option>
                        }
                        <option value="All">All</option>
                    </select>
                </div>
            </div>
        </form>
    </div>

    <div class="row mt-5 mb-5" style="overflow-y: auto;">

        @foreach (var s in Model)
        {
            <div class="col-lg-4 col-md-4 mb-4">
                <div class="card h-100">
                    <img class="card-img-top w-100" src="@s.ImageUrl" style="height: 250px; width: 100px" alt="@s.Title">
                    <div class="card-body">
                        <h4 class="card-title d-flex justify-content-between">
                            <small>Title: @s.Title</small>
                            <small>Genre: @s.Type.Type</small>
                        </h4>
                        @if (s.Author == null)
                        {
                            <h5>Author: @nullAuthor</h5>
                        }
                        else
                        {
                            <h5>Author: @s.Author.Username</h5>
                        }
                        <hr />
                        <p class="card-text">@s.Summary</p>
                    </div>
                    <div class="card-footer">
                        <a small class="text-muted card-link" id="@s.Title" asp-controller="Stories" asp-action="Details" asp-route-id="@s.Id" as>Go to Story</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="mt-5">
    </div>
</div>
@section scripts{
    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }

    <script>
        $("select").change(function () {
            $("#myForm").submit();
        });
    </script>

}

AspNetCourseProject/FanFictionApp/Views/Stories/CreateStory.cshtml
@model StoryInputModel
@inject IStoryService StoryService
@{
    ViewData["Title"] = "CreateStory";
    var genres = this.StoryService.Genres().Select(x => x.Type).ToList();
}

<div class=" row container d-flex  col-md-12" style="margin-top: 100px">
    <div class=" offset-3 col-md-6 border align-content-between border-left border-bottom border-right border-top">

        <h2 class="d-flex justify-content-center">@ViewData["Title"] </h2>
        <hr class="h2" />

        <form role="form" enctype="multipart/form-data" method="post" asp-area="" asp-controller="Stories" asp-action="CreateStory">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Title" class="d-flex justify-content-center "></label>
                        <input asp-for="Title" class="form-control" placeholder="Title..." />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <p class="text-center">Select Genre</p>
                        <select name="Genre" class="col-md-12">
                            <option selected class="text-center" disabled="disabled">choose Genre</option>
                            @foreach (var r in genres)
                            {
                                <option class="text-center">@r</option>
                            }
                        </select>
                        <span asp-validation-for="Genre" class="text-danger"></span>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <p class="row ml-1">Story Image</p>
                            <input type="file" asp-for="StoryImage" name="StoryImage" />
                            @if (ViewData.ContainsKey(GlobalConstants.Error))
                            {
                                <div class="row col-md-12">
                                    <span class="row ml-1 text-danger ">@ViewData[GlobalConstants.Error]</span>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Summary" class="d-flex justify-content-center "></label>
                        <textarea asp-for="Summary" class="form-control" type="text" rows="6"></textarea>
                        <span asp-validation-for="Summary" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input asp-for="Author" class="form-control" placeholder="Author..." name="Author" value="@this.User.Identity.Name" type="hidden" />
                        <input asp-for="CreatedOn" class="form-control" placeholder="CreatedOn..." name="CreatedOn" value="@DateTime.UtcNow" type="hidden" />
                    </div>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="d-flex  col-md-12">
                    <button type="submit" class="btn btn-info btn-block" id="CreateStoryButton">Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }

}

AspNetCourseProject/FanFictionApp/Views/Stories/Details.cshtml
@model StoryDetailsOutputModel
@inject IStoryService service
@inject UserManager<FanFictionUser> manager
@{
    ViewData["Title"] = "Details";

    bool owner = this.User.Identity.Name == Model.Author;
    var user = await this.manager.FindByNameAsync(this.User.Identity.Name);
    var followed = this.service.IsFollowed(user.Id, Model.Id);
    bool rated = this.service.AlreadyRated(Model.Id, this.User.Identity.Name);

}

<div class="row col-md-12">

    <div class="col-md-4">
        <div class="card w-100">
            <img class="card-img-top" src="@Model.ImageUrl" alt="Card image cap" style="height:250px">
            <div class="card-body ">
                <h5 class="card-title">Title:  @Model.Title</h5>
                <hr />
                <p class=" card-text">@Model.Summary</p>
            </div>
            <ul class="list-group list-group-flush">
                @if (Model.Author == null)
                {
                    <li><a class="list-group-item">Author: @GlobalConstants.DeletedUser</a></li>

                }
                else
                {
                    <li><a class="list-group-item card-link" asp-action="Profile" asp-controller="Users" asp-area="" asp-route-username="@Model.Author">Author: @Model.Author</a></li>

                }
                <li class="list-group-item">Created on: @Model.CreatedOn</li>
                <li class="list-group-item">Last edit on: @Model.LastEditedOn</li>
                <li class="list-group-item">Rating: @Model.Rating</li>
            </ul>
            <div class="card-body btn-group-justified">
                @if (owner)
                {
                    <div class="container d-flex justify-content-between">

                        <a asp-area="" asp-action="DeleteStory" asp-controller="Stories" asp-route-id="@Model.Id" class="btn btn-primary"><i class="far fa-trash-alt">Delete</i> </a>
                        <a asp-area="" asp-action="AddChapter" asp-controller="Chapters" asp-route-id="@Model.Id" class="btn btn-primary"><i class="fas fa-plus-square">Chapter</i></a>
                    </div>
                }
                @if (followed && !owner)
                {
                    <a asp-area="" asp-action="UnFollow" asp-controller="Stories" asp-route-id="@Model.Id" class="btn btn-primary">UnFollow </a>

                }
                @if (!owner && !followed)
                {
                    <a asp-action="Follow" asp-controller="Stories" asp-area="" asp-route-id="@Model.Id" class="btn btn-primary">Follow</a>

                }
            </div>

            @if (!owner && !rated)
            {
                <hr />
                <div class="card-body">
                    <form asp-action="AddRating" asp-controller="Stories" method="post">
                        <div class="form-group">
                            <select name="Rating" class="col-md-12">
                                <option selected class="text-center" disabled="disabled">Rate The Story!</option>
                                @for (var r = 1; r <= 10; r++)
                                {
                                    <option class="text-center">@r</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" value="@Model.Id" name="storyId" hidden="hidden" />
                        </div>
                        <div>
                            <button type="submit">Add Rating</button>
                        </div>
                    </form>
                </div>

            }
        </div>
    </div>
    <div class="col-md-6 border border-dark w-100 mb-1" style="max-height:800px;overflow-y:auto">

        @await Component.InvokeAsync("ChapterList", new { storyId = @Model.Id })
    </div>
    <div class="col-md-2">
        @await Component.InvokeAsync("CommentsList", new { storyId = @Model.Id })

        <div class="card w-100 mt-1 d-flex">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body container-flex">
                <form asp-action="AddComment" asp-controller="Comments" asp-area="" method="post">
                    <div class="form-group">
                        <input type="text" hidden="hidden" value="@Model.Id" name="StoryId" />
                        <input type="datetime" hidden="hidden" value="@DateTime.UtcNow" name="CommentedOn" />
                        <input hidden="hidden" type="text" value="@user.UserName" name="CommentAuthor" />
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Enter your comment" rows="4" name="message" id="my-input" maxlength="100"></textarea>
                        <span id='remainingC'></span>
                        @if (this.TempData.ContainsKey(GlobalConstants.Error))
                        {
                            <span>@TempData[GlobalConstants.Error]</span>
                        }
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-plus-square">Comment</i></button>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{

    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
    <script>
        $(document).ready(function () {
            var len = 0;
            var maxchar = 100;

            $('#my-input').keyup(function () {
                len = this.value.length;
                if (len > maxchar) {
                    return false;
                } else if (len > 0) {
                    $("#remainingC").html("Remaining characters: " + (maxchar - len));
                } else {
                    $("#remainingC").html("Remaining characters: " + (maxchar));
                }
            })
        });
    </script>

}

AspNetCourseProject/FanFictionApp/Views/Stories/FollowedStories.cshtml
@model IEnumerable<StoryOutputModel>
@inject IStoryService Service
@{
    ViewData["Title"] = "FollowedStories";
    var genres = this.Service.Genres();
    var nullAuthor = GlobalConstants.DeletedUser;
}

<div class="container-fluid">
    <div class="row mt-5 col-md-3">
        <form id="myForm" asp-action="FollowedStories" asp-controller="Stories">
            <div class="form-row align-items-center">
                <div class="col-auto">
                    <select class="custom-select mr-sm-2" name="type" onchange="this.form.submit">
                        <option selected>Choose...</option>
                        @foreach (var g in genres)
                        {
                        <option value="@g.Type">@g.Type</option>
                        }
                        <option value="All">All</option>
                    </select>
                </div>
            </div>
        </form>
    </div>

    <div class="row mt-5 mb-5" style="overflow-y: auto;">

        @foreach (var s in Model)
        {
        <div class="col-lg-4 col-md-4 mb-4">
            <div class="card h-100">
                <img class="card-img-top w-100" src="@s.ImageUrl" style="height: 250px; width: 100px" alt="@s.Title">
                <div class="card-body">
                    <h4 class="card-title d-flex justify-content-between">
                        <small>Title: @s.Title</small>
                        <small>Genre: @s.Type.Type</small>
                    </h4>
                    @if (s.Author==null)
                        {
                    <h5>Author: @nullAuthor</h5>
                        }
                        else
                        {
                    <h5>Author: @s.Author.Username</h5>
                        }
                    <hr />
                    <p class="card-text">@s.Summary</p>
                </div>
                <div class="card-footer">
                    <a small class="text-muted card-link" asp-controller="Stories" asp-action="Details" asp-route-id="@s.Id" as>Go to Story</a>
                </div>
            </div>
        </div>
        }
    </div>
    <div class="mt-5">
    </div>
</div>
@section scripts{
    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }

    <script>
        $("select").change(function () {
            $("#myForm").submit();
        });
    </script>

}

AspNetCourseProject/FanFictionApp/Views/Stories/UserStories.cshtml
@model IEnumerable<StoryOutputModel>

@{
    ViewData["Title"] = "AllStories";
    string username = ViewData[GlobalConstants.UsernameHolder].ToString();
    bool author = this.User.Identity.Name == username;
}

<div class="container-fluid">
    <div class="row mt-5 col-md-3">
        @if (author)
        {
            <a class="btn btn-dark" asp-action="CreateStory" asp-controller="Stories">Add Story</a>
        }
    </div>
    <div class="row mt-5 mb-5" style="overflow-y: auto;">

        @foreach (var s in Model)
        {
            <div class="col-lg-4 col-md-4 mb-4">
                <div class="card h-100">
                    <img class="card-img-top w-100" src="@s.ImageUrl" alt="@s.Title" style="height: 250px;">
                    <div class="card-body">
                        <h4 class="card-title d-flex justify-content-between">
                            <small>Title: @s.Title</small>
                            <small>Genre: @s.Type.Type</small>
                        </h4>

                        <hr />
                        <p class="card-text">@s.Summary</p>
                    </div>
                    <div class="card-footer">
                        <a small class="text-muted card-link text-info" asp-controller="Stories" asp-action="Details" asp-route-id="@s.Id" as>Go to Story</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="mt-5">
    </div>
</div>
@section scripts{
    @{ await Html.RenderPartialAsync("_MyScriptsPartial"); }
}